## Known Issues
1. Python multiprocessing error 'ForkAwareLocal' object has no attribute 'connection'  
Perhaps you were using Pycharm with Run with Python console option checked in Run/Debug Configuration. Try uncheck that. [Reference](https://stackoverflow.com/questions/60795412/python-multiprocessing-error-forkawarelocal-object-has-no-attribute-connectio)
